acme_hello_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Hello:index }
acme_hello_test:
    pattern : /test/{name}
    defaults: {_controller: AcmeHelloBundle:Hello:test, color: red }
acme_hello_redirect:
    pattern : /r
    defaults: {_controller: AcmeHelloBundle:Hello:helloRedirect }
